### ISSUE TITLE
避免使用保留名字

### ISSUE THREAD

**Issue by YexuanXiao** [RFoe/coasync#1]
https://github.com/RFoe/coasync/blob/a466688370ce4bc5feefc8a55d960de447dfbfde/include/coasync/detail/spin_loop_pause.hpp#L15
https://github.com/RFoe/coasync/blob/a466688370ce4bc5feefc8a55d960de447dfbfde/include/coasync/detail/get_id.hpp#L24
等等。
[保留标识符](https://zh.cppreference.com/w/cpp/language/identifiers)：
* 在全局命名空间中，以一个下划线开始的标识符
* 除以下标识符外（略）**任何位置带有双下划线或以单下划线后随一个大写字母**开始的标识符

**Comment by RFoe** [comment]
嗯，确实是不好的习惯。我在不久后会改正过来
